.PHONY: clean fresh run gendeps

LDFLAGS   += -pthread
OBJECTS		= castro.o fileio.o gtpgeneral.o gtpplayer.o gtpsolver.o string.o \
				solverab.o solverpns.o solverpns2.o solverpns_tt.o player.o playeruct.o zobrist.o alarm.o

ifdef DEBUG
	CPPFLAGS	+= -g3 -Wall
else
	CPPFLAGS	+= -O3 -funroll-loops -Wall

	OSTYPE := $(shell uname -s)
	ifeq ($(OSTYPE),Darwin)
		CPPFLAGS += -m64
		LDFLAGS += -m64
	else
		CPPFLAGS += -march=native
	endif
endif



all: castro

mm: mm.cpp
	g++ -O3 -Wall -o mm mm.cpp

castro: $(OBJECTS)
	$(CXX) $(LDFLAGS) -o $@ $^ $(LOADLIBES) $(LDLIBS)


clean:
	rm -f *.o castro mm mm-with-freq.dat

fresh: clean all

profile:
	valgrind --tool=callgrind ./castro

gendeps:
	ls *.cpp -1 | xargs -L 1 cpp -M -MM

############ everything below is generated by: make gendeps

alarm.o: alarm.cpp alarm.h time.h
castro.o: castro.cpp havannahgtp.h gtp.h string.h game.h board.h move.h \
 zobrist.h types.h hashset.h solver.h solverab.h solverpns.h \
 compacttree.h thread.h lbdist.h log.h solverpns2.h solverpns_tt.h \
 player.h time.h depthstats.h xorshift.h weightedrandtree.h
fileio.o: fileio.cpp fileio.h
gtpgeneral.o: gtpgeneral.cpp havannahgtp.h gtp.h string.h game.h board.h \
 move.h zobrist.h types.h hashset.h solver.h solverab.h solverpns.h \
 compacttree.h thread.h lbdist.h log.h solverpns2.h solverpns_tt.h \
 player.h time.h depthstats.h xorshift.h weightedrandtree.h
gtpplayer.o: gtpplayer.cpp havannahgtp.h gtp.h string.h game.h board.h \
 move.h zobrist.h types.h hashset.h solver.h solverab.h solverpns.h \
 compacttree.h thread.h lbdist.h log.h solverpns2.h solverpns_tt.h \
 player.h time.h depthstats.h xorshift.h weightedrandtree.h fileio.h
gtpsolver.o: gtpsolver.cpp havannahgtp.h gtp.h string.h game.h board.h \
 move.h zobrist.h types.h hashset.h solver.h solverab.h solverpns.h \
 compacttree.h thread.h lbdist.h log.h solverpns2.h solverpns_tt.h \
 player.h time.h depthstats.h xorshift.h weightedrandtree.h
mm.o: mm.cpp
player.o: player.cpp player.h time.h types.h move.h string.h board.h \
 zobrist.h hashset.h depthstats.h thread.h xorshift.h weightedrandtree.h \
 lbdist.h compacttree.h log.h solverab.h solver.h solverpns.h alarm.h \
 fileio.h
playeruct.o: playeruct.cpp player.h time.h types.h move.h string.h \
 board.h zobrist.h hashset.h depthstats.h thread.h xorshift.h \
 weightedrandtree.h lbdist.h compacttree.h log.h solverab.h solver.h \
 solverpns.h
solverab.o: solverab.cpp solverab.h solver.h board.h move.h string.h \
 zobrist.h types.h hashset.h time.h alarm.h log.h
solverpns2.o: solverpns2.cpp solverpns2.h solver.h board.h move.h \
 string.h zobrist.h types.h hashset.h compacttree.h thread.h lbdist.h \
 log.h time.h alarm.h
solverpns.o: solverpns.cpp solverpns.h solver.h board.h move.h string.h \
 zobrist.h types.h hashset.h compacttree.h thread.h lbdist.h log.h time.h \
 alarm.h
solverpns_tt.o: solverpns_tt.cpp solverpns_tt.h solver.h board.h move.h \
 string.h zobrist.h types.h hashset.h time.h alarm.h log.h
string.o: string.cpp string.h types.h
zobrist.o: zobrist.cpp zobrist.h types.h

